version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nanoid
    versions:
    - 3.1.20
    - 3.1.21
  - dependency-name: monk
    versions:
    - 7.3.3
  - dependency-name: yup
    versions:
    - 0.32.8
